import KnowledgeCheck from '../components/KnowledgeCheck.jsx'
import PageHero from '../components/PageHero.jsx'

const terms = [['Income', 'Money you receive, such as wages, allowance, or gifts.'], ['Fixed expenses', 'Costs that stay the same each month, such as a transport pass.'], ['Variable expenses', 'Costs that can change, such as snacks or entertainment.'], ['Needs', 'Essentials required for daily life and study.'], ['Wants', 'Optional purchases that improve life but can wait.'], ['Savings', 'Money set aside for goals or unexpected costs.']]
const budget = [['Income: weekend job', 1200], ['Transport pass', -200], ['Basic groceries', -350], ['Phone plan', -100], ['Study supplies', -100], ['Entertainment', -150], ['Savings', -300]]

export default function BudgetingBasicsPage() {
  return <><PageHero eyebrow="Learning module" title="Budgeting Basics"><p>A budget is a simple plan for directing income toward expenses, savings, needs, and wants before money disappears.</p></PageHero><section aria-labelledby="terms-title"><h2 id="terms-title">Six building blocks</h2><div className="concept-grid">{terms.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="example-split" aria-labelledby="example-title"><div><p className="eyebrow">Student example</p><h2 id="example-title">Mona plans her month</h2><p>Mona earns a clearly labeled sample income of 1,200 SAR from weekend work. She protects essentials first, leaves a realistic amount for fun, and saves 300 SAR toward a laptop.</p><div className="budget-bar" aria-label="Sample budget distribution: 750 SAR needs, 150 SAR wants, 300 SAR savings"><span style={{ width: '62.5%' }}>Needs</span><span style={{ width: '12.5%' }}>Wants</span><span style={{ width: '25%' }}>Savings</span></div></div><table aria-label="Sample monthly student budget"><caption>Sample monthly student budget (SAR)</caption><thead><tr><th scope="col">Category</th><th scope="col">Amount</th></tr></thead><tbody>{budget.map(([label, amount]) => <tr key={label}><th scope="row">{label}</th><td>{amount > 0 ? '+' : ''}{amount} SAR</td></tr>)}</tbody><tfoot><tr><th scope="row">Money left</th><td>0 SAR</td></tr></tfoot></table></section><KnowledgeCheck /></>
}
