import { useState } from 'react'
import MoneyField from '../components/MoneyField.jsx'
import PageHero from '../components/PageHero.jsx'
import { expenseSummary } from '../lib/finance.js'
import { plannerEntrySchema } from '../lib/validation.js'
import { usePlannerStore } from '../store/plannerStore.js'
const categories = ['Food', 'Transport', 'Education', 'Entertainment', 'Shopping', 'Utilities', 'Miscellaneous']
const currency = new Intl.NumberFormat('en-SA', { style: 'currency', currency: 'SAR' })
const blank = { date: '', category: '', description: '', amount: '' }
export default function ExpensePlannerPage() {
  const { entries, add, update, remove, reset } = usePlannerStore(), [income, setIncome] = useState(''), [form, setForm] = useState(blank), [errors, setErrors] = useState({}), [editing, setEditing] = useState(null)
  const change = (key) => (e) => setForm({ ...form, [key]: e.target.value }), summary = expenseSummary(Number(income) || 0, entries)
  const submit = (e) => { e.preventDefault(); const parsed = plannerEntrySchema.safeParse({ type: 'expense', category: form.category, amount: form.amount.trim() === '' ? NaN : Number(form.amount) }); const next = {}; if (!form.date) next.date = 'Date is required'; if (!form.description.trim()) next.description = 'Description is required'; if (!parsed.success) parsed.error.issues.forEach((issue) => { next[issue.path[0]] ??= issue.message }); setErrors(next); if (Object.keys(next).length) return; const entry = { ...parsed.data, date: form.date, description: form.description.trim() }; editing ? update(editing, entry) : add(entry); setEditing(null); setForm(blank) }
  const edit = (entry) => { setEditing(entry.id); setForm({ date: entry.date, category: entry.category, description: entry.description, amount: String(entry.amount) }) }
  const resetPlan = () => { if (window.confirm('Reset the entire expense plan?')) { reset(); setIncome(''); setEditing(null); setForm(blank) } }
  return <><PageHero eyebrow="Monthly planner" title="Plan and review your expenses"><p>Add a sample income and expenses to see the balance update immediately.</p></PageHero><p className="session-note">This planner is temporary for this session. Your entries are not permanently stored.</p><section className="planner-summary"><MoneyField id="planner-income" label="Sample monthly income" type="text" value={income} onChange={(e) => setIncome(e.target.value)} /><p>Total expenses: <strong>{currency.format(summary.total)}</strong></p><p>Remaining: <strong>{currency.format(summary.remaining)}</strong></p>{summary.overspent && <p className="warning" role="alert">You are over budget. Review your expenses and adjust the plan.</p>}</section><section className="planner-layout"><form className="tool-card form-grid" onSubmit={submit} noValidate><h2>{editing ? 'Edit expense' : 'Add an expense'}</h2><label className="field" htmlFor="expense-date"><span>Date</span><input id="expense-date" type="date" value={form.date} onChange={change('date')} />{errors.date && <small role="alert">{errors.date}</small>}</label><label className="field" htmlFor="expense-category"><span>Category</span><select id="expense-category" value={form.category} onChange={change('category')}><option value="">Choose a category</option>{categories.map((category) => <option key={category}>{category}</option>)}</select>{errors.category && <small role="alert">{errors.category}</small>}</label><label className="field" htmlFor="expense-description"><span>Description</span><input id="expense-description" value={form.description} onChange={change('description')} />{errors.description && <small role="alert">{errors.description}</small>}</label><MoneyField id="expense-amount" label="Amount" type="text" value={form.amount} onChange={change('amount')} error={errors.amount} /><button className="primary-button">{editing ? 'Save expense' : 'Add expense'}</button></form><div className="tool-card expense-list"><div className="section-heading"><h2>Your expenses</h2><button className="secondary-button" type="button" onClick={resetPlan} disabled={!entries.length}>Reset plan</button></div>{!entries.length ? <p className="empty-state">No expenses yet. Add your first expense to begin.</p> : <div className="table-wrap"><table><caption>Expense entries</caption><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{entries.map((entry) => <tr key={entry.id}><td data-label="Date">{entry.date}</td><td data-label="Category">{entry.category}</td><td data-label="Description">{entry.description}</td><td data-label="Amount">{currency.format(entry.amount)}</td><td data-label="Actions"><button type="button" onClick={() => edit(entry)} aria-label={`Edit ${entry.description}`}>Edit</button><button type="button" onClick={() => remove(entry.id)} aria-label={`Delete ${entry.description}`}>Delete</button></td></tr>)}</tbody></table></div>}</div></section></>
}
