import { useState } from 'react'
import PageHero from '../components/PageHero.jsx'

const mistakes = [['Impulse buying', 'A flash sale makes you buy headphones you did not plan for.', 'Your savings goal is delayed.', 'Wait 24 hours and compare the purchase with your priorities.', 'Remove saved payment details and keep a wish list.'], ['Ignoring small expenses', 'Daily drinks and snacks go unrecorded.', 'Small costs become a large monthly total.', 'Review recent transactions and add them to the plan.', 'Record purchases immediately or check spending weekly.'], ['Late payments', 'A phone bill is forgotten past its due date.', 'Fees grow and service may be interrupted.', 'Pay the bill and contact the provider if help is needed.', 'Use calendar reminders or automatic payments.'], ['Unused subscriptions', 'A streaming service renews even though nobody watches it.', 'Money leaves the account without providing value.', 'Cancel the service and check for a refund policy.', 'Review subscriptions every month.'], ['Spending without a plan', 'Allowance is spent during the first week.', 'Nothing remains for transport and study costs.', 'List income and protect essential categories first.', 'Make a simple budget before spending begins.']]

export default function MoneyMistakesPage() {
  const [open, setOpen] = useState(null)
  return <><PageHero eyebrow="Learning module" title="Five common money mistakes"><p>Recognize the pattern, understand its cost, and use one practical step to prevent it next time.</p></PageHero><section className="accordion" aria-label="Common money mistakes">{mistakes.map(([title, scenario, consequence, action, prevention], index) => { const expanded = open === index; const panel = `mistake-${index}`; return <article key={title}><h2><button type="button" aria-expanded={expanded} aria-controls={panel} onClick={() => setOpen(expanded ? null : index)}><span>{title}</span><span aria-hidden="true">{expanded ? '−' : '+'}</span></button></h2>{expanded && <div id={panel} className="accordion-panel"><p><strong>Scenario:</strong> {scenario}</p><p><strong>Consequence:</strong> {consequence}</p><p><strong>Corrective action:</strong> {action}</p><p><strong>Prevention:</strong> {prevention}</p></div>}</article>})}</section></>
}
